"""empty message

Revision ID: 457e177ff07b
Revises: 7ea6e1391fe5
Create Date: 2024-01-11 09:21:45.395580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457e177ff07b'
down_revision = '7ea6e1391fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Badge_image', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_column('Badge_image')

    # ### end Alembic commands ###
