"""empty message

Revision ID: 7ea6e1391fe5
Revises: 42e917b70d0f
Create Date: 2024-01-11 04:24:00.772591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea6e1391fe5'
down_revision = '42e917b70d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('BadgeID', sa.Integer(), nullable=False),
    sa.Column('BadgeName', sa.Text(), nullable=True),
    sa.Column('Classification', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('BadgeID')
    )
    op.create_table('practice_problems',
    sa.Column('ProblemID', sa.Integer(), nullable=False),
    sa.Column('ProblemStatement', sa.Text(), nullable=True),
    sa.Column('SolvingPoints', sa.Integer(), nullable=True),
    sa.Column('ProblemClass', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ProblemID')
    )
    op.create_table('user_badges',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('BadgeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['BadgeID'], ['badges.BadgeID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('UserID', 'BadgeID')
    )
    op.create_table('user_problems',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('ProblemID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ProblemID'], ['practice_problems.ProblemID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_problems')
    op.drop_table('user_badges')
    op.drop_table('practice_problems')
    op.drop_table('badges')
    # ### end Alembic commands ###
