"""empty message

Revision ID: e5b7fc9041f6
Revises: 457e177ff07b
Create Date: 2024-01-11 10:25:35.743845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b7fc9041f6'
down_revision = '457e177ff07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_league', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_league')
        batch_op.drop_column('total_points')

    # ### end Alembic commands ###
